### PR TITLE
fix(report-aggregate) Fix report aggregation

### PR DESCRIPTION
**Pull request by aurelien-baudet**
- #621: do not use test dependencies as test source directories
- #622: use the name of the mutator (it is not a class name written in mutations.xml)

### CODE REVIEW

**Comment by dan323** [comment]
I would really appreciate if we could have the aggregation fixed

**Comment by aurelien-baudet** [comment]
@hcoles Could you review the PR and merge it if it is OK for you ?

Also for the new score calculation, I could add some screenshots and examples to illustrate the interest if you want

**Comment by aurelien-baudet** [comment]
@hcoles I have rebased the PR with latest changes to fix report aggregation.
I also separate the commit for a new mutation score for multi-project aggregation (I will create another PR for this).

Can you merge with master ?

**Comment by tijanssen** [comment]
I also would like to see this fixed.

**Comment by hcoles** [comment]
@aurelien-baudet Sorry for the silence. If you can resolve the conflicts again and confirm it works, I'll merge this in.

**Comment by aurelien-baudet** [comment]
Sorry but I have currently no time. Moreover, I rebased the code 3 times to resolve conflicts but it had never been merged...

**Pull request merged**
