### PR TITLE
Dec Positions for over all percentage

### PR DESCRIPTION
**Pull request by paul-hammant**
relates to #372 - stop rounding and have three decimal positions

### CODE REVIEW

**Comment by hcoles** [comment]
Thanks for the PR. 

I'll take a proper look when I'm not thumb typing on a phone - but rounding has been an emotive issue for people in the past so some thought might be required.

**Comment by paul-hammant** [comment]
Hey, any thoughts about merging this in, Henry?

**Comment by hcoles** [comment]
Sorry - only just looked.

I think this may need a little more work before it can be merged in. The switch to float means that the an int/float comparison is now taking place when enforcing the mutation threshold.

I haven't quite got my head round what the result of this will be, but to preserve the existing behaviour I think the float will need to be rounded as per the original code when applying the threshold.

The comparison is currently duplicated in the commandline tool and maven plugin (and presumably also the gradle plugin). It should perhaps be made a responsibility of the MutationStatistics class to remove the duplication.

**Comment by paul-hammant** [comment]
About ten years ago I donated a JSON capability to Joe Walnes for his ground breaking [XStream](http://x-stream.github.io/) technology.  No pull-requests back then. He consumed it, then rewrote all of it in a single Svn commit, while still being generous and crediting me.  

At some point, IBM called me to ask about IP as they were using XStream in something that required them to sleuth through the contributors. A little embarrassed, I cooperated fully and confirmed that I was free to make contributions and not restrained by any IP arrangement with my employer (ThoughtWorks).  

I'm quite used to authors liking the idea but moving to the correct implementation :)

More on Joe and open source: https://paulhammant.com/2014/05/26/joe-walnes-on-successful-open-source/

**Comment by paul-hammant** [comment]
> I think this may need a little more work before it can be merged in.

The way Joe would do it would be to merge the change in, then do a follow up commit to improve the float/int logic. And if we're also doing the always release mantra of Joe, we wouldn't mind if there was a release between the one that went out with **this** PR, and the commit that would improve the float/int logic.  i.e. Releasing and consuming community contributions are the most important things for OSS techs that have not jumped to that "have a life of their own" place.

**Comment by paul-hammant** [comment]
Any further thoughts?

**Comment by hcoles** [comment]
The worry was not that the float/int logic would need improving, but that it would result in broken behaviour. Although pitest doesn't release all that frequently I try to keep master in a shippable state.

I've finally found time to check this branch out and try it out (sorry for the slow response). The float/int comparison does not seem to cause any major problems - the limits are still enforced sensibly.

The increased length of the figures does however cause some rendering issues on the html report. If these can be fixed I'd be happy to merge it in.

**Comment by paul-hammant** [comment]
https://paulhammant.com/2014/05/26/joe-walnes-on-successful-open-source/ --> 

.8 Implore potential collaborators to contribute patches (pull requests) that are implementation and tests
.9 Rewrite/Refactor as you speedily consume patches

^ Me writing in 2014 about open source contribution events in 2006.

I'm not going to do any further work on that pull-request. Over to you.

**Comment by UrsMetz** [comment]
@paul-hammant I think your reaction is a bit harsh. The mode you refer to might be nice for the (occasional) contributors.
But I think there are two main reasons for maintainers to follow a policy that differs from your proposed policy like @hcoles does (apart from the releasable master argument):
* restricted time: reworking contributions can be time consuming
* building a contributor basis: I think some people would be a bit upset or confused when their recently merged changes are turned inside out and would rather have been guided to the solution the maintainer prefers. From the project I follow on GitHub and contributed to I'm used to this kind of policy.

**Comment by paul-hammant** [comment]
I regret doing this work. I thought I had deleted it. I deleted my fork that's for sure. The author should just ignore this and do what he wants to do, or not do what he wants to do.

**Pull request closed without merging**
