### PR TITLE
Look for JUnit annotations up in class hierarchy too

### PR DESCRIPTION
**Pull request by Kwaq**
It would be useful if @Category and @RunWith annotations placed on test superclasses could be considered too.

### CODE REVIEW

**Comment by hcoles** [comment]
@Kwaq Does this match how categories behave with surefire?

**Comment by Kwaq** [comment]
Yes. Since JUnit 4.12 @Category has @Inherited added (https://github.com/junit-team/junit4/issues/398).

**Comment by hcoles** [comment]
I think, to match normal junit behaviour, we would need to check that the version of `@Category` on the classpath was annotated with `@Inherited` before navigating up the hierarchy.

**Comment by hcoles** [comment]
Thanks for the PR - sorry it took so long to merge

**Pull request merged**
