### PR TITLE
provide aggregated name for mutator if generated as a collection

### PR DESCRIPTION
**Pull request by ThLeu**
Hi, as I mentioned in my other PR here is also some minor enhancement to aggregate the EXPERIMENTAL_REMOVE_SWITCH_MUTATOR in the report.

Best regards,
ThLeu

### CODE REVIEW

**Comment by ThLeu** [comment]
Hello @hcoles!
What do you think of this change? Would appreciate your feedback.
Best regards

**Comment by hcoles** [comment]
Thanks for the PR.

Just had a quick scan over - what's the purpose of the `isGeneratedAsCollection` flag? It appears that this will always be set to true, apart from in tests.

**Comment by hcoles** [comment]
But yes, since the mutation description includes info about which switch variation was performed there is no need for it to be in the mutator name and this is definitely a big improvement - thanks.

**Comment by ThLeu** [comment]
Thanks for your feedback!
The `isGeneratedAsCollection` is only there because the constructor is public, so I thought that it could and maybe will be used by clients somehow. As alternative the constructor could be set to default visibility (package private) if it is only used in the test, then the flag can be deleted again.

**Comment by ThLeu** [comment]
I changed it now to the mentioned version, if it does not matter that the constructor is package private than this version is probably better.

**Pull request merged**
