### PR TITLE
Mergeup of #625

### PR DESCRIPTION
**Pull request by therealryan**
This is the same changeset as the apparently-stalled #625, but with merge conflicts resolved

The conflicts turned out to be simple:

 * Catch blocks were collapsed in master. These had been deleted in the branch anyway
 * The `MethodName` class has been removed, so no need to call `MethodName.fromString()` (or `name()` in the tests)

### CODE REVIEW

**Comment by hcoles** [comment]
Thanks @therealryan.

The tests around this area of the code are minimal, but that is an existing issue from when this feature was first added. If you can confirm that everthing works as expected when run against a real project I'll merge it in.

**Comment by therealryan** [comment]
After:
1. checking out this branch
2. `mvn install`
3. updating my project to use the 1.0.0-SNAPSHOT version that was generated
4. Adding a `<value>XML</value>` element to `plugin/configuration/outputFormats`

I can confirm that report aggregation works as expected.

**Comment by hcoles** [comment]
@therealryan Thanks, merged now.

**Comment by therealryan** [comment]
Great stuff! All credit to @aurelien-baudet !

**Pull request merged**
