### PR TITLE
make order features applied in consistent

### LINKED ISSUE #1175: Regression with Pitest 1.11.6
One of my tests (which I unfortunately cannot disclose started failing when I bumped Pitest from 1.11.5 to 1.11.6. The project is using `com.groupcdg.pitest:extended-mutators:0.1.5` as well:

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at com.groupcdg.pitest.mutators.swap.parameters.JunkParamSwapInterceptor.paramsHaveMismatchedGenerics(JunkParamSwapInterceptor.java:116)
        at com.groupcdg.pitest.mutators.swap.parameters.JunkParamSwapInterceptor.isJunk(JunkParamSwapInterceptor.java:58)
        at com.groupcdg.pitest.mutators.swap.parameters.JunkParamSwapInterceptor.lambda$isJunkParamSwapMutant$0(JunkParamSwapInterceptor.java:50)
        at java.base/java.util.function.Predicate.lambda$negate$1(Predicate.java:80)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at com.groupcdg.pitest.AnalysingInterceptor.intercept(AnalysingInterceptor.java:33)
        at org.pitest.mutationtest.build.CompoundMutationInterceptor.intercept(CompoundMutationInterceptor.java:51)
        at org.pitest.mutationtest.build.MutationSource.createMutations(MutationSource.java:60)
        at org.pitest.functional.FCollection.flatMapTo(FCollection.java:51)
        at org.pitest.functional.FCollection.flatMap(FCollection.java:61)
        at org.pitest.mutationtest.build.MutationTestBuilder.createMutationTestUnits(MutationTestBuilder.java:59)
        at org.pitest.mutationtest.tooling.MutationCoverage.buildMutationTests(MutationCoverage.java:387)
        at org.pitest.mutationtest.tooling.MutationCoverage.runAnalysis(MutationCoverage.java:166)
        at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:143)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:129)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:57)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:98)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)

### PR DESCRIPTION
**Pull request by hcoles**
Fixes #1175

### CODE REVIEW

**Comment by davidburstrom** [comment]
Is it an option to use https://stackoverflow.com/a/51945053/643007 ?

**Comment by hcoles** [comment]
That would keep the order consistent, but not make it (easily) predictable.

**Comment by davidburstrom** [comment]
True. I'm just thinking that it would preserve the order of the input (e.g. the list of features), whereas if the alphabetical output order isn't viable, it needs to be shuffled on the receiving end. It all depends on the intended contract for `FeatureSelector`.

**Comment by hcoles** [comment]
Order wasn't meant to be important, and hence hadn't been considered before now. Without the explicit alphabetical order, it would be determined by the order plugins are picked up off the classpath. That would introduces further unpredictability and the possibility of different behaviour for the same codebase when run on a different os/some other factor changes. It's easier going forward to have a simple explicit order that a human can understand.

**Comment by davidburstrom** [comment]
Got it. It's true that the crash in the interceptors was only coincidentally related to ordering, it was just a consequence of the argument swapper interceptor being buggy. Let's just hope that the new order doesn't cause any other intermittent issues.

**Pull request merged**
