### PR TITLE
PitMojo.java - make execute() non-final

### PR DESCRIPTION
**Pull request by tclausing**
I want to implement a new MutationResultListener, but it needs additional configuration which the api doesn't provide for. So my intention is to extend PitMojo, add my extra params, store them statically, and use them in my MutationResultListener.

### CODE REVIEW

**Comment by hcoles** [comment]
Creating a subclass of the PitMojo for each custom listener is not a scalable solution for passing configuration around.

A proper mechanism is needed to pass free form data to plugins - it ought to be fairly straightforward to update the current plugin interface to take a Properties object.

**Comment by tclausing** [comment]
To clarify, I need to add dynamic config by way of maven's @parameter.  To do that without duplicating yours, afaik I need to extend PitMojo.  Also, I intend to add my listener as a plugin dependency rather than to the pitest artifact itself, so while I agree it's not scalable, it won't impact your artifact, and for my own use I'm not real concerned about it.

**Comment by tclausing** [comment]
I'm sorry, that probably didn't make much sense. Normally I'd add this stuff in a fork of pitest-maven, but to get that through my org's red tape would not be pleasant, and I'm also hoping to avoid the overhead of keeping up to date with an upstream.

**Comment by hcoles** [comment]
I've just knocked something together locally for #190 so a map of free-form properties can be passed to the plugin from the mojo. I assume this would solve your problem?

**Comment by tclausing** [comment]
Don't the extra params need to be explicit and present at build time so that the plugin descriptor can capture them?

**Comment by hcoles** [comment]
@tclausing Free form key value pairs can be captured in a map.

eg

```
<pluginProperties>
   <foo>fish</foo>
   <bar>cthulhu</bar>
</pluginProperties>
```

**Pull request closed without merging**
